### ISSUE TITLE
[Rust] Cannot package when Cargo.toml is a virtual manifest

### ISSUE THREAD

**Issue by jaudiger** [brioche-dev/brioche-packages#40]
Sometimes the Cargo.toml manifest is [virtual](https://doc.rust-lang.org/cargo/reference/workspaces.html#virtual-workspace) such as the one from Yazi: https://github.com/sxyazi/yazi/blob/main/Cargo.toml

```log
[86768] error: found a virtual manifest at `/home/brioche-runner-f4abbe2f9e9591a1b125ac4143e1e8556e9b9255f3
8b23aa518ecdb47cacda6a/work/Cargo.toml` instead of a package manifest
```

We would need a way to pass some additional arguments to cargo install in order to specify the packages to build and install.

**Comment by kylewlacy** [comment]
I have some stashed changes that should address this. Basically, it would add a new `path` option for `cargoBuild()`, which should allow building crates like this

I'll see if I can grab these and make a PR

**Comment by jaudiger** [comment]
That would resolve indeed this problem. I also encountered it while trying to package another Rust crate.
